#!/usr/bin/env bash
set -euo pipefail
export NO_DNA=1

fail() { echo "Payment localnet initialization failed: $1" >&2; exit 1; }

command -v solana >/dev/null || fail "solana CLI is required"
command -v spl-token >/dev/null || fail "spl-token CLI is required"
command -v node >/dev/null || fail "Node.js is required"
[[ "${SOLANA_CLUSTER:-localnet}" == "localnet" ]] || fail "SOLANA_CLUSTER must be localnet"
[[ -n "${DEMO_BUYER_KEYPAIR:-}" ]] || fail "DEMO_BUYER_KEYPAIR is required"
[[ -n "${DEMO_MERCHANT_PUBLIC_KEY:-}" ]] || fail "DEMO_MERCHANT_PUBLIC_KEY is required"
[[ -f "$DEMO_BUYER_KEYPAIR" ]] || fail "The configured buyer keypair file does not exist"

# Resolve a caller-relative keypair before entering the project for Node imports.
BUYER_KEYPAIR="$(cd -- "$(dirname -- "$DEMO_BUYER_KEYPAIR")" && pwd)/$(basename -- "$DEMO_BUYER_KEYPAIR")"
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."
LOCAL_RPC="${SOLANA_LOCALNET_RPC_URL:-http://127.0.0.1:8899}"
TOKEN_PROGRAM="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

# A prefix check would also accept localhost.evil.example or localhost@evil.example.
node --input-type=module - "$LOCAL_RPC" "$DEMO_MERCHANT_PUBLIC_KEY" <<'JS'
import { address } from "@solana/kit";
try {
  const url = new URL(process.argv[2]);
  if (!["localhost", "127.0.0.1", "[::1]"].includes(url.hostname)
    || !["http:", "https:"].includes(url.protocol)) throw new Error();
} catch {
  console.error("SOLANA_LOCALNET_RPC_URL must use an exact loopback hostname");
  process.exit(1);
}
try {
  address(process.argv[3]);
} catch {
  console.error("DEMO_MERCHANT_PUBLIC_KEY must be a valid Solana public key");
  process.exit(1);
}
JS

BUYER_ADDRESS="$(solana address --keypair "$BUYER_KEYPAIR" 2>/dev/null)" || fail "Cannot read the configured buyer keypair"
[[ -z "${DEMO_BUYER_PUBLIC_KEY:-}" || "$DEMO_BUYER_PUBLIC_KEY" == "$BUYER_ADDRESS" ]] || fail "Buyer keypair does not match DEMO_BUYER_PUBLIC_KEY"
[[ "$BUYER_ADDRESS" != "$DEMO_MERCHANT_PUBLIC_KEY" ]] || fail "Buyer and merchant must be different wallets"

solana cluster-version --url "$LOCAL_RPC" >/dev/null 2>&1 || fail "Start the local validator first: npm run localnet:start"
GENESIS="$(solana genesis-hash --url "$LOCAL_RPC" 2>/dev/null)" || fail "Cannot verify the local validator genesis hash"
[[ "$GENESIS" =~ ^[1-9A-HJ-NP-Za-km-z]{32,44}$ ]] || fail "The validator returned an invalid genesis hash"
case "$GENESIS" in
  EtWTRABZaYq6iMfeYKouRu166VU2xqa1*|5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp*)
    fail "Public Devnet and Mainnet are disabled in this local initializer" ;;
esac
NETWORK="solana:${GENESIS:0:32}"
[[ -z "${SOLANA_LOCALNET_NETWORK:-}" || "$SOLANA_LOCALNET_NETWORK" == "$NETWORK" ]] || fail "SOLANA_LOCALNET_NETWORK does not match the running validator"

solana airdrop 2 "$BUYER_ADDRESS" --url "$LOCAL_RPC" --keypair "$BUYER_KEYPAIR" >/dev/null 2>&1 || fail "Local test SOL airdrop failed"
SPL_OPTIONS=(--url "$LOCAL_RPC" --program-id "$TOKEN_PROGRAM" --fee-payer "$BUYER_KEYPAIR")

# A fresh ephemeral mint is generated by spl-token; no keypair files are created.
MINT_OUTPUT="$(spl-token create-token "${SPL_OPTIONS[@]}" --decimals 6 --mint-authority "$BUYER_ADDRESS" 2>/dev/null)" || fail "Creating the classic SPL test mint failed"
MINT="$(printf '%s\n' "$MINT_OUTPUT" | node --input-type=module -e '
  import { address } from "@solana/kit";
  import { readFileSync } from "node:fs";
  const match = readFileSync(0, "utf8").match(/^Address:\s+([1-9A-HJ-NP-Za-km-z]{32,44})\s*$/m);
  try { if (!match) throw new Error(); console.log(address(match[1])); }
  catch { process.exit(1); }
')" || fail "Cannot parse the new mint address; inspect the local validator before retrying"

spl-token create-account "$MINT" "${SPL_OPTIONS[@]}" --owner "$BUYER_ADDRESS" >/dev/null 2>&1 || fail "Creating the buyer token account failed"
spl-token create-account "$MINT" "${SPL_OPTIONS[@]}" --owner "$DEMO_MERCHANT_PUBLIC_KEY" >/dev/null 2>&1 || fail "Creating the merchant token account failed"
spl-token mint "$MINT" 1 "${SPL_OPTIONS[@]}" --mint-authority "$BUYER_KEYPAIR" --recipient-owner "$BUYER_ADDRESS" >/dev/null 2>&1 || fail "Minting the buyer's local test tokens failed"

# Public configuration only: do not print keypair paths or potentially secret RPC URLs.
printf '%s\n' "# Localnet initialized with 1 local test USDC." \
  "SOLANA_CLUSTER=localnet" \
  "SOLANA_LOCALNET_NETWORK=$NETWORK" \
  "LOCAL_USDC_MINT=$MINT" \
  "DEMO_BUYER_PUBLIC_KEY=$BUYER_ADDRESS" \
  "DEMO_MERCHANT_PUBLIC_KEY=$DEMO_MERCHANT_PUBLIC_KEY"
